[package]
name = "whatadistro"
version = "0.1.0"
description = "Rust library to identify your linux distribution"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "MIT"
edition = "2021"
